"use client";
import {useRef,useEffect} from "react";
import styles from "./HomeImmersive.module.css";
import {useKetherEffects} from "./KetherEffectsProvider";
export default function HomeCinema(){const ref=useRef<HTMLCanvasElement>(null);const {effectiveMode}=useKetherEffects();useEffect(()=>{const canvas=ref.current;if(!canvas)return;const context=canvas.getContext('2d');if(!context)return;if(effectiveMode==="eco"){context.clearRect(0,0,canvas.width,canvas.height);return;}const ctx:CanvasRenderingContext2D=context;let cw=0,ch=0,lastFrame=0,cinemaFrame=0,cinemaTime=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');function sizeCinema(){const d=Math.min(devicePixelRatio||1,1.25);cw=innerWidth;ch=innerHeight;canvas.width=cw*d;canvas.height=ch*d;ctx.setTransform(d,0,0,d,0,0)}sizeCinema();addEventListener('resize',sizeCinema);const motes=Array.from({length:innerWidth<600?(effectiveMode==="full"?70:24):(effectiveMode==="full"?115:44)},()=>({x:Math.random(),y:Math.random(),depth:Math.random(),phase:Math.random()*6.28}));
function drawCinema(t:number){if(document.hidden)return;if(t-lastFrame>(effectiveMode==="full"?33:66)||reduced.matches){const dt=Math.min((t-lastFrame)/1000,.05);lastFrame=t;if(!reduced.matches)cinemaTime+=dt;const seconds=cinemaTime;ctx.clearRect(0,0,cw,ch);ctx.globalCompositeOperation='screen';
// Broad moving volumetric light: illumination changes independently of the poster.
for(let i=0;i<(effectiveMode==="full"?3:1);i++){const x=cw*(.53+i*.17)+Math.sin(seconds*.23+i)*cw*.1,y=ch*(.12+Math.sin(seconds*.15+i)*.12),radius=cw*(.28+i*.04),glow=ctx.createRadialGradient(x,y,0,x,y,radius);glow.addColorStop(0,i===1?'rgba(224,185,116,.23)':'rgba(68,215,217,.23)');glow.addColorStop(.35,'rgba(62,140,180,.08)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,cw,ch)}
// Slow energy waves and anamorphic flare pass across the distant scene.
for(let i=0;i<2;i++){const phase=((seconds*.055+i*.5)%1),x=cw*(.48+phase*.43),y=ch*.43,alpha=Math.sin(phase*Math.PI)*.3;ctx.save();ctx.translate(x,y);ctx.scale(1,.56);ctx.beginPath();ctx.ellipse(0,0,40+phase*cw*.62,55+phase*cw*.62,0,0,Math.PI*2);ctx.strokeStyle='rgba(133,241,232,'+alpha+')';ctx.lineWidth=1.5;ctx.shadowBlur=22;ctx.shadowColor='#74fff2';ctx.stroke();ctx.restore()}
const flareX=cw*(.73+Math.sin(seconds*.17)*.1),flareY=ch*(.32+Math.cos(seconds*.11)*.08),flare=ctx.createRadialGradient(flareX,flareY,0,flareX,flareY,cw*.29);flare.addColorStop(0,'rgba(188,255,244,.5)');flare.addColorStop(.08,'rgba(127,225,240,.2)');flare.addColorStop(1,'rgba(0,0,0,0)');ctx.save();ctx.translate(0,flareY);ctx.scale(1,.022);ctx.translate(0,-flareY);ctx.fillStyle=flare;ctx.fillRect(0,flareY-cw*.3,cw,cw*.6);ctx.restore();
for(const p of motes){const depth=p.depth,x=(p.x*cw+Math.sin(seconds*.2+p.phase)*30+seconds*(3+depth*18))%cw,y=((p.y*ch-seconds*(5+depth*23))%ch+ch)%ch,r=.55+depth*depth*5,alpha=.16+.48*(1+Math.sin(seconds*.5+p.phase))/2;ctx.beginPath();ctx.fillStyle='rgba('+(depth>.78?'244,215,158,':'151,240,235,')+alpha+')';ctx.shadowColor=depth>.78?'#f1c47e':'#8bffec';ctx.shadowBlur=effectiveMode==="full"?depth*16:0;ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();if(depth>.88){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-7,y+18);ctx.strokeStyle='rgba(235,211,151,.17)';ctx.lineWidth=1;ctx.stroke()}}ctx.shadowBlur=0;ctx.globalCompositeOperation='source-over';}if(!reduced.matches)cinemaFrame=requestAnimationFrame(drawCinema)}
function resumeCinema(){cancelAnimationFrame(cinemaFrame);lastFrame=0;if(!document.hidden)cinemaFrame=requestAnimationFrame(drawCinema)}resumeCinema();document.addEventListener('visibilitychange',resumeCinema);reduced.addEventListener('change',resumeCinema);

return ()=>{cancelAnimationFrame(cinemaFrame);removeEventListener("resize",sizeCinema);document.removeEventListener("visibilitychange",resumeCinema);reduced.removeEventListener("change",resumeCinema)};},[effectiveMode]);return <canvas ref={ref} className={styles.cinema}/>;}