import crypto from "node:crypto";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const SITE_URL = "https://kether-warframe-database.vercel.app";

const INTERACTION_TYPE = {
  PING: 1,
    APPLICATION_COMMAND: 2,
    };

    const RESPONSE_TYPE = {
      PONG: 1,
        CHANNEL_MESSAGE_WITH_SOURCE: 4,
        };

        const LINKS = [
          {
              title: "KETHER Warframe 資料庫首頁",
                  url: `${SITE_URL}/`,
                      description: "氏族資料庫首頁。",
                          keywords: ["首頁", "home", "網站", "kether", "資料庫"],
                            },
                              {
                                  title: "資料庫總覽",
                                      url: `${SITE_URL}/database/overview`,
                                          description: "查看分類統計、追價、完成率與總覽資料。",
                                              keywords: ["總覽", "overview", "統計", "完成率", "追價"],
                                                },
                                                  {
                                                      title: "戰甲資料",
                                                          url: `${SITE_URL}/database/warframes`,
                                                              description: "查詢戰甲相關資料。",
                                                                  keywords: ["戰甲", "warframe", "warframes", "甲"],
                                                                    },
                                                                      {
                                                                          title: "主要武器資料",
                                                                              url: `${SITE_URL}/database/primary`,
                                                                                  description: "查詢主要武器資料。",
                                                                                      keywords: ["主要武器", "primary", "主武器", "步槍"],
                                                                                        },
                                                                                          {
                                                                                              title: "次要武器資料",
                                                                                                  url: `${SITE_URL}/database/secondary`,
                                                                                                      description: "查詢次要武器資料。",
                                                                                                          keywords: ["次要武器", "secondary", "副武器", "手槍"],
                                                                                                            },
                                                                                                              {
                                                                                                                  title: "近戰武器資料",
                                                                                                                      url: `${SITE_URL}/database/melee`,
                                                                                                                          description: "查詢近戰武器資料。",
                                                                                                                              keywords: ["近戰", "近戰武器", "melee", "刀", "劍"],
                                                                                                                                },
                                                                                                                                  {
                                                                                                                                      title: "同伴資料",
                                                                                                                                          url: `${SITE_URL}/database/companions`,
                                                                                                                                              description: "查詢同伴、寵物相關資料。",
                                                                                                                                                  keywords: ["同伴", "寵物", "companions", "pet", "庫狛", "庫娃"],
                                                                                                                                                    },
                                                                                                                                                      {
                                                                                                                                                          title: "曲翼資料",
                                                                                                                                                              url: `${SITE_URL}/database/archwing`,
                                                                                                                                                                  description: "查詢曲翼、曲翼武器與亡靈骸甲相關資料。",
                                                                                                                                                                      keywords: ["曲翼", "archwing", "亡靈骸甲", "necramech"],
                                                                                                                                                                        },
                                                                                                                                                                          {
                                                                                                                                                                              title: "MOD 資料庫",
                                                                                                                                                                                  url: `${SITE_URL}/database/mods`,
                                                                                                                                                                                      description: "查詢 MOD、卡片、系列 MOD 與追價資料。",
                                                                                                                                                                                          keywords: ["mod", "MOD", "模組", "卡片", "p版mod", "prime mod", "系列mod"],
                                                                                                                                                                                            },
                                                                                                                                                                                              {
                                                                                                                                                                                                  title: "官方公告",
                                                                                                                                                                                                      url: `${SITE_URL}/notifications`,
                                                                                                                                                                                                          description: "查看 Warframe 官方公告與通知資料。",
                                                                                                                                                                                                              keywords: ["官方", "公告", "新聞", "news", "更新", "通知"],
                                                                                                                                                                                                                },
                                                                                                                                                                                                                  {
                                                                                                                                                                                                                      title: "資料庫狀態",
                                                                                                                                                                                                                          url: `${SITE_URL}/db-status`,
                                                                                                                                                                                                                              description: "查看資料庫同步與狀態頁。",
                                                                                                                                                                                                                                  keywords: ["狀態", "status", "資料庫狀態", "同步"],
                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                          title: "個人進度",
                                                                                                                                                                                                                                              url: `${SITE_URL}/profile`,
                                                                                                                                                                                                                                                  description: "查看 Discord 登入後的個人已購買進度。",
                                                                                                                                                                                                                                                      keywords: ["個人", "進度", "profile", "已購買", "購買"],
                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                        function jsonResponse(body: unknown, status = 200) {
                                                                                                                                                                                                                                                          return new Response(JSON.stringify(body), {
                                                                                                                                                                                                                                                              status,
                                                                                                                                                                                                                                                                  headers: {
                                                                                                                                                                                                                                                                        "Content-Type": "application/json",
                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                              function verifyDiscordRequest(rawBody: string, signature: string | null, timestamp: string | null) {
                                                                                                                                                                                                                                                                                const publicKey = process.env.DISCORD_PUBLIC_KEY?.trim();

                                                                                                                                                                                                                                                                                  if (!publicKey || !signature || !timestamp) {
                                                                                                                                                                                                                                                                                      return false;
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                              const publicKeyBytes = Buffer.from(publicKey, "hex");

                                                                                                                                                                                                                                                                                                  if (publicKeyBytes.length !== 32) {
                                                                                                                                                                                                                                                                                                        return false;
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                const spkiPrefix = Buffer.from("302a300506032b6570032100", "hex");
                                                                                                                                                                                                                                                                                                                    const key = crypto.createPublicKey({
                                                                                                                                                                                                                                                                                                                          key: Buffer.concat([spkiPrefix, publicKeyBytes]),
                                                                                                                                                                                                                                                                                                                                format: "der",
                                                                                                                                                                                                                                                                                                                                      type: "spki",
                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                              return crypto.verify(
                                                                                                                                                                                                                                                                                                                                                    null,
                                                                                                                                                                                                                                                                                                                                                          Buffer.from(timestamp + rawBody),
                                                                                                                                                                                                                                                                                                                                                                key,
                                                                                                                                                                                                                                                                                                                                                                      Buffer.from(signature, "hex")
                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                            } catch {
                                                                                                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                  function searchLinks(keyword: string) {
                                                                                                                                                                                                                                                                                                                                                                                    const text = keyword.toLowerCase().trim();

                                                                                                                                                                                                                                                                                                                                                                                      if (!text) {
                                                                                                                                                                                                                                                                                                                                                                                          return LINKS.slice(0, 6);
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                              return LINKS.filter((item) => {
                                                                                                                                                                                                                                                                                                                                                                                                  const haystack = [
                                                                                                                                                                                                                                                                                                                                                                                                        item.title,
                                                                                                                                                                                                                                                                                                                                                                                                              item.description,
                                                                                                                                                                                                                                                                                                                                                                                                                    item.url,
                                                                                                                                                                                                                                                                                                                                                                                                                          ...item.keywords,
                                                                                                                                                                                                                                                                                                                                                                                                                              ]
                                                                                                                                                                                                                                                                                                                                                                                                                                    .join(" ")
                                                                                                                                                                                                                                                                                                                                                                                                                                          .toLowerCase();

                                                                                                                                                                                                                                                                                                                                                                                                                                              return haystack.includes(text);
                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                function buildMessage(keyword: string) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  const results = searchLinks(keyword);

                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (results.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              content:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `找不到「${keyword}」相關資料喵。\n` +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "可以試試：首頁、總覽、戰甲、主要武器、次要武器、近戰、同伴、曲翼、MOD、官方、個人進度。",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flags: 64,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const content = results
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .slice(0, 5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .map((item) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return `**${item.title}**\n${item.description}\n${item.url}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .join("\n\n");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        content,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export async function POST(request: Request) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const signature = request.headers.get("x-signature-ed25519");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const timestamp = request.headers.get("x-signature-timestamp");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const rawBody = await request.text();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const isValid = verifyDiscordRequest(rawBody, signature, timestamp);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!isValid) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return jsonResponse({ error: "Bad request signature" }, 401);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const interaction = JSON.parse(rawBody);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (interaction.type === INTERACTION_TYPE.PING) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return jsonResponse({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type: RESPONSE_TYPE.PONG,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (interaction.type === INTERACTION_TYPE.APPLICATION_COMMAND) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const commandName = interaction.data?.name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const keyword =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              interaction.data?.options?.find((option: { name: string; value?: string }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return option.name === "keyword";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })?.value ?? "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (commandName === "kether") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return jsonResponse({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type: RESPONSE_TYPE.CHANNEL_MESSAGE_WITH_SOURCE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      data: buildMessage(keyword),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return jsonResponse({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type: RESPONSE_TYPE.CHANNEL_MESSAGE_WITH_SOURCE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  content: "小希還沒學會這個指令喵。",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flags: 64,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export async function GET() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return jsonResponse({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ok: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name: "KETHER Discord Bot Endpoint",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }